{{- if and .Values.core.enabled .Values.core.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "core.fullname" . }}-core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: core
  name: {{ template "core.fullname" . }}-core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "core.fullname" . }}-core
  minReplicas: {{ .Values.core.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.core.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.core.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}