{{- if and .Values.core.enabled .Values.core.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "core.fullname" . }}-core-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "core.fullname" . }}-core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: core
spec:
  ports:
  - port: {{ .Values.core.service.port }}
    targetPort: {{ .Values.core.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ template "core.fullname" . }}-core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: core
{{- end }}